In [1]:
import torch

In [5]:
#creates tensor with row vector X
#what is a tensor?
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
#gives back length of x axis
#what does give x.shape back...?
x.shape

torch.Size([12])

In [7]:
#gives back total size of tensor (sum of all elements in the tensor)
x.numel()

12

In [8]:
#what does this command do with the row vector of 12 elements?
#creates matrix with 3 rows and and 4 columns
X = x.reshape
X

<function Tensor.reshape>

In [9]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [14]:
#gaussian normal distribution with with a mean of 0 and standard deviation of 1
torch.randn(3,4)

tensor([[ 1.6485,  1.0263,  0.5992, -0.6202, -0.1214],
        [-1.8018,  1.9056,  1.6896, -0.6910,  1.7229],
        [ 1.1274, -0.8447,  0.7085, -0.5649,  0.1407]])

In [15]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [16]:
x = torch.tensor([1.0, 2,4, 8])
y = torch.tensor([2,2,2,2])
x + y, x - y, x * y, x / y, x**y  # The ** operator is exponentiation

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [17]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [25]:
#creates a row vector x with 0-11 and reshapes it to tensor with 3 rows and 4 columns
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
#concatenates tensors
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [50]:
print("This is X:")
print(X)
print("This is Y:")
print(Y)
X > Y

This is X:
tensor([[38., 37., 40., 39.],
        [37., 38., 39., 40.],
        [28., 30., 32., 34.]])
This is Y:
tensor([[26., 25., 28., 27.],
        [25., 26., 27., 28.],
        [20., 21., 22., 23.]])


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [28]:
X.sum()

tensor(66.)

In [29]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b    

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [30]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [31]:
#slicing
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [33]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [34]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [37]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [38]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 140460749340928
id(Z): 140460749340928


In [39]:
before = id(X)
X += Y
id(X) == before

True

In [40]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [41]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)